### ISSUE TITLE
BlahBlah??

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#35]
![F1FC5888-1FE7-4BF7-B62B-047E331351C9](https://user-images.githubusercontent.com/6731214/132957850-1edb7860-a576-4049-8809-000420a77cbe.jpeg)
Since Sept 9, I get a Non-JSON response: BlahBlah! This is very weird. Any other have the issue? Maybe the URL have changed? On Nissan got hacked? Lol

**Comment by gboudreau** [comment]
Same thing here; my guess: someone @ Nissan (or more likely, a subcontractor) deployed in PROD some debugging code.

**Comment by rtw819** [comment]
Seeing the same, and chuckled.  A small part of me wonders if there is a new or different API endpoint (?) for auth since the Nissan EV&Services app connects and is still working right now with my US 2017 LEAF.  Their app actually seemed speedier than average, and it seems to actually be working at the moment, so that much is hard to complain about.  

It is definitely a strange response from an API call for sure, and not very professional.  :D   Hopefully they figure it out.

**Comment by SDeath667** [comment]
I am seeing something similar:
An error occurred: Non-JSON response received for request to 'BatteryStatusCheckRequest.php'. Response received: "\n\n
Not sure when this started, but very annoying because my code doesn’t work anymore. 
I wonder if the app update had anything to do with a new API endpoint as well. 
I hope this can be fixed.

**Comment by anderslundin-kanari** [comment]
Are you using https://gdcportalgw.its-mo.com/api_v210707_NE/gdc/? If not try it, the older once just expired and gave me the same error.

**Comment by rtw819** [comment]
The US API endpoint seems to have changed, likely with the advent of the pending Ariya release.

From:
```
https://icm.infinitiusa.com/NissanLeafProd/rest/
```

To:
```
https://icm.infinitiusa.com/NissanEVProd/rest/
```

**Comment by gboudreau** [comment]
Looks like the API key sent in headers changed too, because just using that new URL fails with an `Invalid API Key` error.

**Comment by gboudreau** [comment]
Was able to see the new URL and API key by using Charles Debugging Proxy on an iOS device. (It doesn't work on Android anymore, since Android N.)

**Comment by Raiden38** [comment]
Merci énormément!!!! :)

**Comment by SDeath667** [comment]
Should this work for EU based vehicles as well?

**Comment by SDeath667** [comment]
> 
> 
> Are you using https://gdcportalgw.its-mo.com/api_v210707_NE/gdc/? If not try it, the older ones just expired and gave me the same error.

You suggestion worked, just changing the baseURL worked to fix my issue.

**Comment by Raiden38** [comment]
Oh no, it's is starting again with the new link:
Non-JSON response received for request to 'POST https://icm.infinitiusa.com/NissanEVProd/rest/auth/authenticationForAAS'. Response received: BlahBlah
